### PR TITLE
Added Test Coverage for StorageType

### LINKED ISSUE #294: Add `typ` method to `proto.TestRunner`
The proto.TestRunner does not currently have a test for storage.Type. This test needs to be added and applied to the mongo.TestMongo and postgres.TestPostgres.

### PR DESCRIPTION
**Pull request by pixalquarks**
Resolves #294 

### Changes
- Added method for testing storage type
- Added test case for testing the type of storage db for both Mongo and Postgres.

### CODE REVIEW

**Comment by prestonvasquez** [comment]
@pixalquarks Can we fix the linting error here?

**Comment by pixalquarks** [comment]
@prestonvasquez can you resolve the conflicts please

**Comment by pixalquarks** [comment]
@prestonvasquez  Hey, can you fix this issues please, linter doesn't seem to be working well on my local machine.

**Comment by prestonvasquez** [comment]
@pixalquarks Sure, thank you for the contribution here.

**Pull request merged**
